name: docker
on: push
env:
  name: raham
  client: swiggy
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      server: app server
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: install docker
        uses: docker/setup-docker-action@v4

      - name: build image
        run: docker build -t netflix:v1 .

      - name: tag image
        run: docker tag netflix:v1 yashwanthdutt26/gabimage

